ALTER TABLE "UsoIA" ADD COLUMN "modelo" TEXT;
ALTER TABLE "UsoIA" ADD COLUMN "tokensEntrada" INTEGER;
ALTER TABLE "UsoIA" ADD COLUMN "tokensSaida" INTEGER;
ALTER TABLE "UsoIA" ADD COLUMN "custoEstimadoUsd" DECIMAL(10,6);
